### ISSUE TITLE
APP刷新时异常

### ISSUE THREAD

**Issue by git-xiaocao** [fluttercandies/loading_more_list#39]
APP刷新时 列表也会刷新 然后异常

```
IndexedStack
   xxxWidget
      for(...)
          LoadingMoreList
   xxxWidget
      for(...)
          LoadingMoreList
   LoadingMoreSliverList
  
```

Ctrl + S 热重载 和 Get.updateLocal() 所有列表都会刷新 异常发生于LoadingMoreSliverList

<details>
  <summary>终端输出</summary>

```console
The following RangeError was thrown building:
RangeError (index): Invalid value: Valid value range is empty: 1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:260:36)
#1      LoadingMoreBase.[] (package:loading_more_list_library/src/loading_more_list_library.dart:26:37)
#2      LoadingMoreListConfig.buildItem (package:loading_more_list/src/list_config/loading_more_list_config.dart:144:17)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:457:22)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1215:28)
#5      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1148:67)
#6      Iterable.forEach (dart:core/iterable.dart:279:35)
#7      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1192:24)
#8      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1126:7)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#21     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#56     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#66     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#78     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#82     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#95     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#105    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#106    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#118    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#120    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#126    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#142    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#146    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#151    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#160    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#170    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#174    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#175    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#176    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#177    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#178    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#179    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following RangeError was thrown building:
RangeError (index): Invalid value: Valid value range is empty: 2

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:260:36)
#1      LoadingMoreBase.[] (package:loading_more_list_library/src/loading_more_list_library.dart:26:37)
#2      LoadingMoreListConfig.buildItem (package:loading_more_list/src/list_config/loading_more_list_config.dart:144:17)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:457:22)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1215:28)
#5      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1148:67)
#6      Iterable.forEach (dart:core/iterable.dart:279:35)
#7      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1192:24)
#8      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1126:7)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#21     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#40     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#52     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#56     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#66     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#78     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#82     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#95     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#99     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#105    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626:32)
#106    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284:17)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#111    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#115    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#118    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#120    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#122    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#126    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#131    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#132    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#133    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#142    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#146    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#151    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#160    StatefulElement.update (package:flutter/src/widgets/framework.dart:4795:5)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:4943:5)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6130:14)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#170    StatelessElement.update (package:flutter/src/widgets/framework.dart:4669:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#174    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#175    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#176    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#177    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#178    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#179    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
```
</details>

**Comment by zyl4265097** [comment]
差不多同样的问题，也提示
The getter 'rebuild' was called on null.
Receiver: null
Tried calling: rebuild

LoadingMoreList LoadingMoreSliverList 都会出现

**Comment by zmtzawqlp** [comment]
你们应该确认下自己的列表加载的代码，不要在没有数据的请求回来的时候去 clear掉数据。
